### ISSUE TITLE
Q: Could you give me an detailed example about how to solve a CVRP problem using your trained model?

### ISSUE THREAD

**Issue by JiaxinWang-thu** [mit-wu-lab/learning-to-delegate#2]
Thanks for your novel idea and beautiful codes~
I am a green hand there. I would like to solve a CVRP problem using your trained model. But it seems difficult to get familiar with so many functions. I have no idea about in what order they should be called.
Therefore, I am here for your kindful help. Could someone give an example? Thanks a lot!

**Comment by ZhongxiaYan** [comment]
Hi! I just saw this now, thank you for your interest in our work but unfortunately I'm quite busy at the moment and cannot provide you with more detailed instructions beyond what I clarify below:

There's an overview on the Readme https://github.com/mit-wu-lab/learning-to-delegate#overview , and essentially if you want to just run a trained model on a CVRP problem instance, you would run steps 1 and 3 (skipping 2 and 4 since you don't need to train or use baselines). For steps 1 and 3, you should click into the links to see the commands that we run. You will need to modify step 1 to insert the problem instance that you want to solve, I'll leave it to you to figure this out.

A tip regarding dealing with the number of functions in a project: I suggest that you can try to follow the two commands in steps 1 and 3 and essentially try to follow where the code goes. You can either follow the code in your head or use a debugger if necessary. This is the best way to deal with code complexity. We already try our best to keep things as organized as possible.

**Comment by qingspring** [comment]
I also encounter the same issue. I found it hard to figure out how to use the pretrained model and subsolver to solve CVRP directly. Could you provide some examples or a main function?  Thanks.

**Comment by ZhongxiaYan** [comment]
Sigh, these are good points, unfortunately both of us are busy with summer internships at the moment, not sure when we can get to making a run script. It shouldn't be hard to be honest, we just haven't touched the code in a while, I'll respond here if I do get time to do this though

**Comment by jokofa** [comment]
Hi, thanks for the work! I wanted to check if there is any progress on these issues? 

I also have problems for the case when I want to create some solution trajectories.
Just trying for a uniform500 model to generate some solution trajectories on the uniform1000 val data.
If I run with the following specifications as described in "Generating Solution Trajectories"

```
export TRAIN_DIR=exps/uniform_N500_routeneighbors10/rotate_flip_augnode0.05_augroute0.005_xfc_ln_lr0.001 # Directory for regression or classification model
export GENERATE_CHECKPOINT_STEP=40000

export N=1000 # options: [500,1000,2000,3000]
export SAVE_DIR=generations/uniform_N$N

export GENERATE_SAVE_DIR=$SAVE_DIR # This should be set as described above
export GENERATE_PARTITION=val # options: [val,test]
export GENERATE_SUFFIX=_val # A suffix which helps distinguish between different $GENERATE_SAVE_DIR

export DEPTH=1000 # respectively for N = [500,1000,2000,3000], use [400,600,1200,2000] for K = 10 or [1000,2000,3000,4500] for K = 5
export N_INSTANCES=10
export N_RUNS=1 # use 1 for experimentation to save time
export N_CPUS=1

export DATASET_DIR=$SAVE_DIR

python supervised.py $DATASET_DIR $TRAIN_DIR --generate --step $GENERATE_CHECKPOINT_STEP --generate_partition $GENERATE_PARTITION --save_dir $GENERATE_SAVE_DIR --save_suffix $GENERATE_SUFFIX --generate_depth $DEPTH --generate_index_start 0 --generate_index_end $N_INSTANCES --n_lkh_trials 500 --n_trajectories $N_RUNS --n_cpus $N_CPUS --device cpu
```


I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'generations/uniform_N1000/val_routeneighbors10.npz'


Now there is a folder val_routeneighbors10 with 40 .npz files in there, but how are they combined into the required dataset?
There is no further information on that and it is not easily deducted from you code what needs to be done. 


I basically want to run your model as a baseline to compare against my model but it is not straight forward to just execute one of your model checkpoints even on the same val/test data. 

For example, how would I run the Uniform500 model on the uniform1000 val data? In the readme you write 

> When we evaluate trained models on a particular problem size N, we set the GENERATE_SAVE_DIR to correspond to the SAVE_DIR for that particular N. Similarly, if we would like to run the model on other data (e.g. clustered data), we change GENERATE_SAVE_DIR to be the SAVE_DIR of the target data.

but that does not work. Your help would be much appreciated.

**Comment by ZhongxiaYan** [comment]
Did you generate the uniform1000 data? From the commands that you sent above, I don't see where you ran the commands to generate the uniform1000 data. The data need to be generated into the SAVE_DIR before you run supervised.py. The instructions for generating the data is the first step https://github.com/mit-wu-lab/learning-to-delegate#generating-problem-instances

**Comment by ZhongxiaYan** [comment]
And unfortunately we're still doing internships and don't have much bandwidth at the moment to write a run script. I'd encourage that you take a closer look at the code in the meantime as it's not that complicated overall

**Comment by jokofa** [comment]
Dear Zhongxia Yan,

Thank you for the fast reply!


> Did you generate the uniform1000 data? From the commands that you sent above, I don't see where you ran the commands to generate the uniform1000 data. The data need to be generated into the SAVE_DIR before you run supervised.py. The instructions for generating the data is the first step https://github.com/mit-wu-lab/learning-to-delegate#generating-problem-instances

I have downloaded the zip file and there is the problems_val.npz and problems_test.npz files in the uniform_N1000 directory. 
If I want to generate the data it tells me that it already exists, which is correct.

Basically the task is super simple: 
Run the checkpoint
exps/uniform_N500_routeneighbors10/rotate_flip_augnode0.05_augroute0.005_xfc_ln_lr0.001
to generate the trajectories on that val data and test data.

I now tried for several hours to do that without any progress, and that is as far as I will go.

I am sorry, basically you have a really long readme file but it is not described how to re-produce your experiment evaluation, in particular the code fragments there are not comprehensive. E.g. how should I set the DATASET_DIR when generating trajectories? There are only placeholders but unfortunately not 1 explicit example which one could simply run and check if everything is working.

> And unfortunately we're still doing internships and don't have much bandwidth at the moment to write a run script. I'd encourage that you take a closer look at the code in the meantime as it's not that complicated overall

Since it is your code and you have run that evaluation once, it should only take you a few minutes to show one inference example that works (e.g. the one to create the trajectories for uniform2000 used in the jupyter notebook), if the code is not that complicated, as you say. 

From there I most likely should be able to figure it out. Otherwise, I am not able to use your code in any reasonable way as a baseline. In particular, since you do not provide the trajectories for the test data in the zip file.

**Comment by ZhongxiaYan** [comment]
Yeah this is fair, I'll see if I can create an explicit example soonish. Of course the explicit example may not span all of the functionalities

**Comment by gustav3d** [comment]
Thanks !

**Comment by jokofa** [comment]
> Yeah this is fair, I'll see if I can create an explicit example soonish. 

Thanks a lot, much appreciated!

> Of course the explicit example may not span all of the functionalities

Sure, that is not what I expect :)

**Comment by ZhongxiaYan** [comment]
Hey guys, sorry I just got the time to take a look. I can see why you guys are confused now and I do owe you an apology: I made a mistake in writing in the README:
> If only using trained model checkpoints from the zip file, you can skip straight to [Generating Solution Trajectories](https://github.com/mit-wu-lab/learning-to-delegate#generating-solution-trajectories)"

In particular, the $DATASET_DIR referenced in [Generating Solution Trajectories](https://github.com/mit-wu-lab/learning-to-delegate#generating-solution-trajectories) is a result of running Preprocessing Training and Validation Data (which is described for [regression](https://github.com/mit-wu-lab/learning-to-delegate#preprocessing-training-and-validation-data) and [classification](https://github.com/mit-wu-lab/learning-to-delegate#preprocessing-training-and-validation-data-1) separately. This is because some of the model's parameter dimensions depends on the original validation data that the model is trained on (in particular [`d_node` and `d_route`](https://github.com/mit-wu-lab/learning-to-delegate/blob/main/supervised.py#L226) which are the feature dimensions). So for running a uniform_N500 model on uniform_N1000 data, you still need to preprocess uniform_N500's validation data so that it can be used to create the uniform_N500 model.

So, taking the example commands from your original question above which wants to run the classification model of uniform_N500 on the uniform_N1000 data: you need to first run (replace `$ROOT` with your root) 
```
export ROOT=<your path to>/learning-to-delegate

export DATASET_DIR=$ROOT/generations/uniform_N500/subproblem_selection_lkh
export K=10 # options: [5,10]
export DEPTH=30 # This should be the same as the depth used in Generating Training and Validation Data
export N_CPUS=2

python preprocess.py $DATASET_DIR val --n_route_neighbors $K --generate_depth $DEPTH --n_cpus $N_CPUS
```

This will generate the preprocessed validation file `$DATASET_DIR/val_routeneighbors10.npz`.

Then you can run (note that this uses the `$DATASET_DIR` defined during preprocessing):
```
export DATASET_DIR=$ROOT/generations/uniform_N500/subproblem_selection_lkh
export TRAIN_DIR=$ROOT/exps/uniform_N500_routeneighbors10/rotate_flip_augnode0.05_augroute0.005_xfc_ln_lr0.001 # Directory for regression or classification model
export GENERATE_CHECKPOINT_STEP=40000

export GENERATE_SAVE_DIR=$ROOT/generations/uniform_N1000 # This should be set as described above
export GENERATE_PARTITION=val # options: [val,test]
export GENERATE_SUFFIX=_uniform_N1000_val # A suffix which helps distinguish between different $GENERATE_SAVE_DIR

export DEPTH=6000 # respectively for N = [500,1000,2000,3000], use [400,600,1200,2000] for K = 10 or [1000,2000,3000,4500] for K = 5
export N_INSTANCES=2 # using 2 instead of 40 for experimentation to save time
export N_RUNS=2 # using 2 instead of 5 for experimentation to save time
export N_CPUS=2

MKL_NUM_THREADS=1 python supervised.py $DATASET_DIR $TRAIN_DIR --generate --step $GENERATE_CHECKPOINT_STEP --generate_partition $GENERATE_PARTITION --save_dir $GENERATE_SAVE_DIR --save_suffix $GENERATE_SUFFIX --generate_depth $DEPTH --generate_index_start 0 --generate_index_end $N_INSTANCES --n_lkh_trials 500 --n_trajectories $N_RUNS --n_cpus $N_CPUS --device cpu
```

Let me know if this helps and I can update the README accordingly

**Comment by jokofa** [comment]
Great, thanks a lot! 
I will try it out as soon as I have the time.

**Comment by jokofa** [comment]
I tried with your example and I got a bit further than before. 
However, now I am encountering errors when loading the checkpoint. 
I did some search online and it seems to be caused by incompatible versions of pytorch/torch-geometric.
Could you please tell me the exact versions you are using in your environment?

**Comment by jokofa** [comment]
OK, so it seems the major version conflict came from pytorch-geometric which requires the version 1.7.2 compared to newer versions (>= 2.x) to work with the checkpoints properly. 

Just for anyone else who is struggling to run the code,
I could finally make it work with the following exact versions setup:

```
conda install pytorch==1.9.1 cudatoolkit=10.2 -c pytorch
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.9.1+cu102.html
pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.9.1+cu102.html
pip install torch-geometric==1.7.2
```

**Comment by ZhongxiaYan** [comment]
Ahh, sorry I forgot to respond yesterday with the versions. Thanks for sharing these!
